requires-python = ">=3.11,<3.12"

dependencies = [
    "fastapi==0.111.0",
    "pydantic==2.8.2",
    "pydantic-core==2.20.1",
    "uvicorn==0.30.6",
    "python-dotenv==1.0.1",
    "openai-agents==0.6.2",
    "openai==1.40.0",
    "python-frontmatter==1.1.0",
    "qdrant-client==1.11.1",
    "google-generativeai==0.8.3",
    "starlette==0.40.0"
]
